T6/feat/frontend/formular
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #13
Opened 2024-09-04 16:17 UTC by dampherrr

2024-09-05 07:06 UTC, Agraheris approved these changes

2024-09-05 07:57 UTC, monica-tech75 approved these changes
Good for me

2024-09-05 13:35 UTC, kpeset requested changes

2024-09-05 13:35 UTC, kpeset commented on client/src/components/ArtworkComponent.jsx
> +    <section key={artwork.id} className="artworkcomponent_expo_img">
Le key n'est pas utile

2024-09-05 13:35 UTC, kpeset commented on client/src/pages/Homepage.jsx
> +        <button className="homePage_navButtons" type="button">
Mettre des Link

2024-09-05 13:35 UTC, kpeset commented on client/src/components/ArtworkForm.jsx
> +function ArtworkForm() {
On fait sauter ArtworkForm pour le moment

2024-09-05 14:18 UTC, dampherrr commented on client/src/pages/Homepage.jsx
> +        <button className="homePage_navButtons" type="button">
Utilisation de usenavigate

2024-09-05 15:08 UTC, kpeset requested changes

2024-09-05 15:08 UTC, kpeset commented on client/package.json
> +    "@harmonia/client": "file:",
Il faut supprimer ça. Je sais pas ce que c'est.

2024-09-05 15:08 UTC, kpeset commented on client/src/components/ArtworkComponent.jsx
> +    <section key={artwork.id} className="artworkcomponent_expo_img">
C'est à résoudre avant le merge

2024-09-05 16:18 UTC, dampherrr commented on client/src/components/ArtworkComponent.jsx
> +    <section key={artwork.id} className="artworkcomponent_expo_img">
C'est bon résolu

2024-09-05 20:11 UTC, dampherrr commented on client/package.json
> +    "@harmonia/client": "file:",
Dans package.json:
ligne 777:
`    "node_modules/@harmonia/client": {
      "resolved": "",
      "link": true
    },`

Dans package-lock.json:
ligne 1391:
`    "node_modules/@harmonia/client": {
      "resolved": "",
      "link": true
    },`

impossible à supprimer, quand je supprime les lignes elles reviennent directement.
Dois je vraiment insister pour la suppression?

2024-09-06 08:00 UTC, kpeset requested changes

2024-09-06 08:30 UTC, kpeset approved these changes

2024-09-06 08:30 UTC, merged