Feat/t6/artist page
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #16
Opened 2024-09-06 17:41 UTC by dampherrr

2024-09-09 08:33 UTC, Agraheris approved these changes
Ok (a part le code commenté mais vu avec Damien)

2024-09-09 13:33 UTC, kpeset requested changes

2024-09-09 13:33 UTC, kpeset commented on client/src/components/ArtworkComponent.jsx
> +        {/* <h3>{artwork.artist_name}</h3>
Code mort à supprimer

2024-09-09 13:33 UTC, kpeset commented on client/package.json
> +    "@harmonia/client": "file:",
à supprimer du package.json (pas le lock)

2024-09-09 13:33 UTC, kpeset commented on client/src/pages/ArtistList.jsx
> +      <Navbar />;<h1>Nos artistes</h1>
Ce point virgule a une utilité ^^?

2024-09-10 14:06 UTC, BaptisteFredj requested changes
Enlever les navbars importées dans les différentes pages (elles sont déjà dans App.jsx)

2024-09-10 14:06 UTC, BaptisteFredj commented on client/src/pages/ArtistList.jsx
> +      <Navbar />
Le composant Navbar n'est-il pas déjà importé dans App.jsx ?

2024-09-10 14:06 UTC, BaptisteFredj commented on client/src/pages/ArtworkPage.jsx
> +      <Navbar />
Même cas ici ?

2024-09-10 14:06 UTC, BaptisteFredj commented on client/src/pages/ArtworksPage.jsx
> +      <Navbar />
Ici aussi

2024-09-10 14:06 UTC, BaptisteFredj commented on client/src/pages/ExhibitionPage.jsx
> +      <Navbar />
Ici aussi

2024-09-10 14:12 UTC, kpeset approved these changes

2024-09-10 14:15 UTC, BaptisteFredj approved these changes
Top !

2024-09-10 14:15 UTC, BaptisteFredj commented on server/database/schema.sql
> +    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT null,
question : N'y aurait-il pas des espaces en trop ?

2024-09-10 14:15 UTC, merged