Exhibition page
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #18
Opened 2024-09-09 15:07 UTC by Ryokoh-974

2024-09-09 15:33 UTC, monica-tech75 approved these changes
Good job!!

2024-09-09 21:42 UTC, Agraheris requested changes
Je comprend pas pour le schema SQL?

2024-09-09 21:42 UTC, Agraheris commented on server/database/schema.sql
Pourquoi tu a supprimé tous le Insert Into artwork?

2024-09-10 07:12 UTC, monica-tech75 commented on server/database/schema.sql
si tu regarde ,ça est l'ancient insert et si tu monte le nouvelle insert into est plus aut dans la page

2024-09-10 15:02 UTC, merged