Create ExhibitionForm for add and delete artwork in exhibition
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #19
Opened 2024-09-10 14:05 UTC by Agraheris

2024-09-10 14:31 UTC, BaptisteFredj approved these changes
Top !

2024-09-10 15:11 UTC, Ryokoh-974 approved these changes
check done

2024-09-11 06:49 UTC, kpeset requested changes

2024-09-11 06:49 UTC, kpeset commented on client/src/components/exhibitionForm/AddArtworkComponent.jsx
> +  useEffect(() => {
Ce code me parait un peu compliqué à maintenir et peu cohérent avec le reste de l'appli.
Il faudrait privilégier la chose suivante : 
- Faire la requête API pour avoir les artworks depuis le loader dans le composant parent et le transmettre via les props.

2024-09-12 12:21 UTC, kpeset approved these changes

2024-09-12 12:21 UTC, merged