Us02 artwork form
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #20
Opened 2024-09-11 09:24 UTC by monica-tech75

Change the useState to only one useState

2024-09-12 08:04 UTC, Agraheris approved these changes
Pensé a retirer le console.info sur artworkActions.js (signalé a monica)

2024-09-13 09:19 UTC, dampherrr approved these changes
✅

2024-09-13 14:33 UTC, dampherrr commented
✅

2024-09-17 07:35 UTC, BaptisteFredj submitted a review, later dismissed

2024-09-17 07:38 UTC, kpeset requested changes

2024-09-17 07:38 UTC, kpeset commented on client/src/components/ArtworkForm.jsx
> +    date: new Date().toISOString().split("T")[0],
Il est préférable que la date soit générée par le back via mysql :)

2024-09-17 07:38 UTC, kpeset commented on client/src/components/ArtworkForm.jsx
> +      .post("http://localhost:3310/api/artworks", formData)
Pourquoi en dur et pas via le .env ?

2024-09-17 08:08 UTC, monica-tech75 commented on client/src/components/ArtworkForm.jsx
> +      .post("http://localhost:3310/api/artworks", formData)
sorry

2024-09-17 10:31 UTC, monica-tech75 commented
je vais fermer la pull request et faire une de nouveaux

2024-09-17 10:33 UTC, monica-tech75 commented
je essais de reouvrir

2024-09-17 11:05 UTC, kpeset approved these changes

2024-09-17 11:05 UTC, merged