Feat/backend authentification
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #23
Opened 2024-09-12 14:36 UTC by dampherrr

2024-09-12 15:19 UTC, Ryokoh-974 commented on server/app/controllers/userActions.js
> +    console.info(users);
a enlever

2024-09-13 09:08 UTC, Agraheris approved these changes

2024-09-13 10:05 UTC, kpeset requested changes
Très bien ! Il faut supprimer tout ce qui est en lien avec item.
Nous n'avons pas besoin de cette table, repo, actions.

2024-09-13 10:36 UTC, dampherrr commented
> Très bien ! Il faut supprimer tout ce qui est en lien avec item. Nous n'avons pas besoin de cette table, repo, actions.

Fait!

2024-09-13 12:15 UTC, kpeset approved these changes
Parfait :)

2024-09-13 12:15 UTC, merged