create full back-end for favorites page CRUD test with postman query
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #28
Opened 2024-09-13 10:14 UTC by Ryokoh-974

2024-09-13 10:53 UTC, dampherrr approved these changes
✅

2024-09-13 12:02 UTC, Agraheris approved these changes
Mais peut etre la prochaine fois ne pas push les fichiez totalement commenté (favoriteComponent)

2024-09-17 07:41 UTC, kpeset requested changes

2024-09-17 07:41 UTC, kpeset commented on client/src/components/FavoriteComponent.jsx
> +// import { Link } from "react-router-dom";
Supprimer ces commentaires

2024-09-17 09:17 UTC, kpeset approved these changes

2024-09-17 09:18 UTC, merged