Feat: Authentification Frontend (pages, context, component)
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #30
Opened 2024-09-13 12:54 UTC by dampherrr

2024-09-13 12:59 UTC, Agraheris approved these changes

2024-09-13 14:38 UTC, monica-tech75 approved these changes
Good for me

2024-09-17 07:43 UTC, kpeset requested changes
Je ne veux pas de sous composants dans le formulaire.
Pas de passwordIpput component etc..
ça rend le code compliqué à lire, et à maintenir.

2024-09-17 07:57 UTC, dampherrr commented
> Je ne veux pas de sous composants dans le formulaire. Pas de passwordIpput component etc.. ça rend le code compliqué à lire, et à maintenir.

Peux tu confirmer les composants que tu ne souhaite pas: 
BackButtonComponent ❔
ConfirmPasswordInputComponent ✅
PasswordInputComponent ✅
SentencePasswordCheckComponent ❔
ToggleSwitchComponent ❔

2024-09-17 13:47 UTC, kpeset requested changes

2024-09-17 13:47 UTC, kpeset commented on client/src/main.jsx
> +        loader: () => fetch(`${import.meta.env.VITE_API_URL}/api/users`),
Fonction dans les services avec utilisation d'axios

2024-09-17 13:47 UTC, kpeset commented on client/src/pages/authentification_pages/AuthPage.jsx
> +      <main>
A supprimer

2024-09-17 13:47 UTC, kpeset commented on client/src/pages/authentification_pages/LoginPage.jsx
> +  const emailRef = useRef();
Pas besoin d'utiliser le useRef
Utilisation du hook useState

2024-09-17 13:47 UTC, kpeset commented on client/src/pages/authentification_pages/RegisterPage.jsx
> +  const nameRef = useRef();
Utilisation du useState

2024-09-17 13:47 UTC, kpeset commented on client/src/pages/authentification_pages/RegisterPage.jsx
> +        const response = await fetch(
No fetch :) Mais axios

2024-09-17 18:25 UTC, dampherrr commented on client/src/main.jsx
> +        loader: () => fetch(`${import.meta.env.VITE_API_URL}/api/users`),
✅

2024-09-17 18:27 UTC, dampherrr commented on client/src/pages/authentification_pages/AuthPage.jsx
> +      <main>
✅

2024-09-17 18:44 UTC, dampherrr commented on client/src/pages/authentification_pages/LoginPage.jsx
> +  const emailRef = useRef();
✅

2024-09-17 18:44 UTC, dampherrr commented on client/src/pages/authentification_pages/RegisterPage.jsx
> +  const nameRef = useRef();
✅

2024-09-18 08:14 UTC, merged