Carousel homepage
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #31
Opened 2024-09-13 12:59 UTC by monica-tech75

2024-09-17 07:38 UTC, dampherrr approved these changes
✅

2024-09-17 07:41 UTC, BaptisteFredj approved these changes

2024-09-17 07:47 UTC, kpeset requested changes

2024-09-17 07:47 UTC, kpeset commented on client/src/components/CarouselHomepage.jsx
> +  const artworkLength = Object.keys(carouselArtwork).length;
Renommer carouselArtwork, alors que les autres variables sont exhibition et artist

2024-09-17 07:47 UTC, kpeset commented on client/src/components/CarouselHomepage.jsx
> +  const artistLength = Object.keys(artist).length;
Je ne comprends pas le système de randomisation avec Object.keys

2024-09-17 07:54 UTC, monica-tech75 commented on client/src/components/CarouselHomepage.jsx
> +  const artistLength = Object.keys(artist).length;
c'est pour savoir la longuer de l'object et pouvoir sortir un numero random en depend de la longuer de l'objet

2024-09-17 07:55 UTC, monica-tech75 commented on client/src/components/CarouselHomepage.jsx
> +  const artworkLength = Object.keys(carouselArtwork).length;
tu a raison, je change le props par artwork

2024-09-19 13:32 UTC, kpeset approved these changes

2024-09-19 13:32 UTC, merged