Allartistspage
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #4
Opened 2024-08-29 14:53 UTC by BaptisteFredj

2024-08-29 14:55 UTC, dampherrr approved these changes
✅

2024-08-29 14:58 UTC, Agraheris approved these changes
c'est ok chez moi

2024-08-30 06:50 UTC, kpeset requested changes

2024-08-30 06:50 UTC, kpeset commented on client/src/pages/ArtistList.jsx
> +      {artists.map((artist) => (
A mettre dans un compsant

2024-08-30 06:50 UTC, kpeset commented on client/src/services/request.js
> +    .get("http://localhost:3310/api/artists")
Il faut pas mettre l'URI en dur mais avec ce qu'il y a dans le .env

2024-08-30 06:50 UTC, kpeset commented on server/app/config.js
>        process.env.CLIENT_URL, // keep this one, after checking the value in `server/.env`
Suppression de la ligne 34, 35

2024-08-30 11:39 UTC, kpeset approved these changes

2024-08-30 11:39 UTC, merged