Feat/user interface
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #40
Opened 2024-09-23 07:38 UTC by dampherrr

2024-09-23 19:26 UTC, Ryokoh-974 commented on client/src/components/user_connected_components/ConfirmDeleteComponent.jsx
> +      console.info(deleteAccount);
je peux me tromper bien-sûr mais le   "console.info(deleteAccount);" ligne 22
on peut l'enlever non ?

2024-09-23 19:27 UTC, Ryokoh-974 commented on client/src/pages/user_connected_pages/PersonalInformationsPage.jsx
> +        console.info(res);
je peux me tromper bien-sûr mais le   "console.info(res);" ligne 69
on peut l'enlever non ?

2024-09-23 19:28 UTC, Ryokoh-974 requested changes
il y a 2   "console.info"  qu'on peut enlever je pense.

2024-09-24 12:12 UTC, Agraheris approved these changes

2024-09-24 12:45 UTC, BaptisteFredj approved these changes

2024-09-24 13:27 UTC, kpeset commented on server/app/controllers/userActions.js
> +  const user = { ...req.body, id: req.params.id };
Pourquoi récupérer ce qui provient du body ?

2024-09-25 08:42 UTC, kpeset requested changes

2024-09-25 08:42 UTC, kpeset commented on server/app/controllers/userActions.js
> +  const user = { id: req.params.id };
Il faudrait que l'id ne proviennent pas des params mais plutôt du token jwt qui est à l'intérieur du cookie.
Car avec ce code, une personne mal intentionnée peut supprimer le compte de n'importe quel utilisateur du moment qu'il a son id.

2024-09-25 09:17 UTC, kpeset approved these changes

2024-09-25 09:18 UTC, merged