create page ArtworkPage.jsx for one artwork with back and front
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974 pull request #7
Opened 2024-08-30 09:07 UTC by Ryokoh-974

2024-08-30 10:28 UTC, Agraheris approved these changes
ok

2024-08-30 10:30 UTC, dampherrr approved these changes
✅Validé

2024-09-02 15:27 UTC, kpeset requested changes

2024-09-02 15:27 UTC, kpeset commented on client/src/pages/ArtworkPage.jsx
> +          src="../src/assets/images/maison.png"
Les fichiers statiques doivent être stockés sur le backend dans le dossier public.

2024-09-02 15:27 UTC, kpeset commented on client/src/pages/ArtworkPage.jsx
> +          className="artworkPage_chemin_img"
Je ne comprends pas le nom donnés aux classes.

2024-09-02 15:27 UTC, kpeset commented on client/src/pages/ArtworkPage.jsx
> +        <h1 className="artworkPage_suivi_page">
Jamais de français.

2024-09-03 12:57 UTC, kpeset requested changes

2024-09-03 12:57 UTC, kpeset commented on client/src/pages/ArtworkPage.jsx
> +          src="./server/public/assets/images/logo_house.png"
le src doit être http://localhost:3310/assets/images/fichier

localhost -> qui provient du .env

2024-09-03 13:52 UTC, kpeset approved these changes

2024-09-03 13:53 UTC, merged